# Generated by Django 3.2.3 on 2021-07-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(0, 'Open'), (1, 'Closed')], default='open', max_length=10),
        ),
    ]
