# Generated by Django 3.2.3 on 2021-07-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='todo.Task'),
        ),
    ]
