# Generated by Django 5.0.6 on 2024-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_usertask_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='todo.task'),
        ),
    ]
